# Clean your Data With NumPy and Pandas

In [1]:
#Import Library
import numpy as np
import pandas as pd

In [2]:
# Read Data from your datasets folder
data = pd.read_csv('../datasets/clean-data/Book.csv')

In [3]:
# Create DataFrame from the CSV file
data.head() # To see First Five entery with column names

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

# Data exploration and Basic Hygiene

In [4]:
# Print Missing value
print(data.isnull().sum())

Identifier                   0
Edition Statement         7514
Place of Publication         0
Date of Publication        181
Publisher                 4195
Title                        0
Author                    1778
Contributors                 0
Corporate Author          8287
Corporate Contributors    8287
Former owner              8286
Engraver                  8287
Issuance type                0
Flickr URL                   0
Shelfmarks                   0
dtype: int64

In [5]:
# Drop columns with any missing values 
c=data.dropna(axis='columns')
c.head()

,Identifier,Place of Publication,Title,Contributors,Issuance type,Flickr URL,Shelfmarks
0,206,London,Walter Forbes. [A novel.] By A. A,"FORBES, Walter.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,London; Virtue & Yorston,All for Greed. [A novel. The dedication signed...,"BLAZE DE BURY, Marie Pauline Rose - Baroness",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,London,Love the Avenger. By the author of “All for Gr...,"BLAZE DE BURY, Marie Pauline Rose - Baroness",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,London,"Welsh Sketches, chiefly ecclesiastical, to the...","Appleyard, Ernest Silvanus.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,London,"[The World in which I live, and my place in it...","BROOME, John Henry.",monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [6]:
# Missing value is not Found as it is removed
print(c.isnull().sum())

Identifier              0
Place of Publication    0
Title                   0
Contributors            0
Issuance type           0
Flickr URL              0
Shelfmarks              0
dtype: int64

In [7]:
# Drop the rows where at least one element is missing.
data.dropna()

Empty DataFrame
Columns: [Identifier, Edition Statement, Place of Publication, Date of Publication, Publisher, Title, Author, Contributors, Corporate Author, Corporate Contributors, Former owner, Engraver, Issuance type, Flickr URL, Shelfmarks]
Index: []

Link For Data operation using pandas 
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html

# We can remove columns by passing columns names directly to columns parameters

### data.drop(columns=drop_col, inplace=True)
### data.head()

In [8]:
# drop unnessary columns 
# inplace and axis make change to object
# axis =1 drop column wise axis =0 for row wise
drop_col = ['Edition Statement',
           'Corporate Author',
           'Corporate Contributors',
           'Former owner',
           'Engraver',
           'Contributors',
           'Issuance type',
           'Shelfmarks']

data.drop(drop_col, inplace = True, axis = 1)
data.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [9]:
# Missing value is not Found as it is removed
print(data.isnull().sum())

Identifier                 0
Place of Publication       0
Date of Publication      181
Publisher               4195
Title                      0
Author                  1778
Flickr URL                 0
dtype: int64

# Change Index of Dataframe

In [10]:
# Check unique values in  Columns
data['Identifier'].is_unique

True

In [11]:
data['Place of Publication'].is_unique

False

In [12]:
data['Date of Publication'].is_unique

False

In [13]:
data['Publisher'].is_unique

False

In [14]:
data['Title'].is_unique

False

In [15]:
data['Author'].is_unique

False

In [16]:
data['Flickr URL'].is_unique

True

In [17]:
# Replace the existing index with column name with unique value using set_index :
# To make change directly to object
data.set_index('Identifier', inplace=True)
data.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

### Replace the existing index with column name with unique value using set_index :
### data = data.set_index('Identifier')
### data.head()

In [18]:
# Access each record with loc[]
data.loc[480]

Place of Publication                                               London
Date of Publication                                                  1857
Publisher                                            Wertheim & Macintosh
Title                   [The World in which I live, and my place in it...
Author                                                          A., E. S.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 480, dtype: object

In [19]:
data.iloc[480]

Place of Publication                                               Oxford
Date of Publication                                                  1846
Publisher                                               John Henry Parker
Title                   The Baptistery ... By the author of “The Cathe...
Author                                                                NaN
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 192427, dtype: object

In [20]:
data.iloc[5]

Place of Publication                                               London
Date of Publication                                                  1875
Publisher                                               William Macintosh
Title                   [The World in which I live, and my place in it...
Author                                                          A., E. S.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 481, dtype: object


    We can see from above with
    loc[] => help in accessing data based on index
       whereas
    iloc[] => help in accessing data based on position
    index [480] data is same as in position [5]

# Clean Fields in the Data

In [21]:
# All data types are in object dtype
data.get_dtype_counts()

object    6
dtype: int64

In [22]:
data.loc[1905:, 'Date of Publication'].head(10)

Identifier
1905           1888
1929    1839, 38-54
2836           1897
2854           1865
2956        1860-63
2957           1873
3017           1866
3131           1899
4598           1814
4884           1820
Name: Date of Publication, dtype: object

<b>As stated above some book have multiple date of publication. Book can have only one date of publication.</b>

<b>We need to enforce a numeric value for date of publication to do calculations as:</b>
<li>Remove square brackets, like present: 1879 [1878]</li>
<li>Convert date ranges to their “start date”, wherever present: 1860-63; 1839, 38-54</li>
<li>Remove the dates like: [1897?] replace them with NumPy’s NaN : </li>
<li>Convert the string NaN to NumPy’s NaN value</li>

In [23]:
ex = data['Date of Publication'].str.extract(r'^(\d{4})', expand=False)
ex.head()

Identifier
206    1879
216    1868
218    1869
472    1851
480    1857
Name: Date of Publication, dtype: object

In [24]:
# Convert to numerical values
data['Date of Publication'] = pd.to_numeric(ex)
data['Date of Publication'].dtypes

dtype('float64')

In [25]:
data['Date of Publication'].isnull().sum() / len(data)

0.11717147339205986

# Use str Methods with NumPy to clean Columns

<b>To clean Place of Publication we use str method with NumPy</b>

In [26]:
data['Place of Publication'].head()

Identifier
206                      London
216    London; Virtue & Yorston
218                      London
472                      London
480                      London
Name: Place of Publication, dtype: object

In [27]:
data.loc[data['Place of Publication']== 'London']

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
481,London,1875.0,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
519,London,1872.0,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.",http://www.flickr.com/photos/britishlibrary/ta...
1143,London,1679.0,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.",http://www.flickr.com/photos/britishlibrary/ta...
2854,London,1865.0,E. Moxon & Co.,"See-Saw; a novel ... Edited [or rather, writte...","ABATI, Francesco.",http://www.flickr.com/photos/britishlibrary/ta...
4884,London,1820.0,J. Hatchard & Son,"Abdallah; or, The Arabian Martyr: a Christian ...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
5382,London,1847.0,Punch Office,The Comic History of England ... With ... colo...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5385,London,NaN,"Bradbury, Agnew & Co.",[The comic history of England ... With twenty ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
5389,London,NaN,"Bradbury, Agnew & Co.",[The Comic History of Rome ... Illustrated by ...,"A'BECKETT, Gilbert Abbott.",http://www.flickr.com/photos/britishlibrary/ta...
6036,London,1805.0,C. & R. Baldwin,"The Venetian Outlaw, a drama in three acts ......",NaN,http://www.flickr.com/photos/britishlibrary/ta...
8435,London,1892.0,Effingham Wilson & Co.,The Witwatersrand Gold Mines. A true and unvar...,"ABRAHAM, Félix - Writer on Mining",http://www.flickr.com/photos/britishlibrary/ta...
8440,London,1894.0,Effingham Wilson,The New Era of the Goldmining Industry in the ...,"ABRAHAM, Félix - Writer on Mining",http://www.flickr.com/photos/britishlibrary/ta...
13074,London,1899.0,W. Thacker & Co.,A Summer in High Asia: being a record of sport...,"ADAIR, Frederick Edward Shafto.",http://www.flickr.com/photos/britishlibrary/ta...
13364,London,NaN,"Griffith, Farran & Co.",A Hand-book and History of Sidmouth from the T...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
14466,London,NaN,Adams & King,"The Historie of Eald Street, now called Old St...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
15141,London,1893.0,T. Fisher Unwin,The New Egypt. A social sketch. [Edited by J. ...,"ADAMS, Francis William Lauderdale.",http://www.flickr.com/photos/britishlibrary/ta...
15146,London,1894.0,T. Fisher Unwin,Tiberius: a drama ... With introduction by W. ...,"ADAMS, Francis William Lauderdale.",http://www.flickr.com/photos/britishlibrary/ta...
16543,London,1816.0,John Murray,"The Narrative of Robert Adams, a sailor, who w...","Adams, Robert - Sailor",http://www.flickr.com/photos/britishlibrary/ta...
17602,London,1897.0,J. Bowden,East End Idylls ... With an introduction by th...,"Adcock, Arthur St. John",http://www.flickr.com/photos/britishlibrary/ta...
18173,London,1804.0,Vernor & Hood,[The Works of the late Right Honourable Joseph...,"ADDISON, Joseph - Right Hon",http://www.flickr.com/photos/britishlibrary/ta...
20960,London,1853.0,Addey & Co.,"The Diary and Houres of the Ladye Adolie, a fa...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
21119,London,1874.0,Chapman & Hall,"Lays of Modern Oxford, by Adon. Illustrated by...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
21430,London,1790.0,J. Johnson,"Adriano; or, the first of June, a poem. By the...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
21782,London,NaN,J. Johnston,The Adventures of a Post Captain. By a Naval O...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
22105,London,1795.0,J. Debrett,"The National Advocates, a poem. Affectionately...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
23565,London,1877.0,Chatto & Windus,Prometheus the Fire-giver. An attempted restor...,Aeschylus.,http://www.flickr.com/photos/britishlibrary/ta...
24878,London,1886.0,Hodder & Stoughton,The Children of Africa. Written for all Englis...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...
3998513,London,1893.0,Macmillan & Co.,Strolling Players. A harmony of contrasts,"Yonge, Charlotte Mary",http://www.flickr.com/photos/britishlibrary/ta...
3998658,London,1843.0,J. B. Nichols & Son,Extracts from the municipal records of the Cit...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
3999230,London,1813.0,NaN,The Rival Roses; or the Wars of York and Lanca...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
4001224,London,1877.0,NaN,Nyassa; a journal of adventures whilst explori...,"YOUNG, Edward Daniel.",http://www.flickr.com/photos/britishlibrary/ta...
4001226,London,1868.0,NaN,The Search after Livingstone. [A diary kept du...,"YOUNG, Edward Daniel.",http://www.flickr.com/photos/britishlibrary/ta...
4001363,London,1898.0,A. Constable & Co.,The Kingdom of the Yellow Robe: being sketches...,"YOUNG, Ernest - F.R.G.S",http://www.flickr.com/photos/britishlibrary/ta...
4002984,London,1858.0,NaN,Miscellaneous Works ... Vols. I. and II. ... e...,"YOUNG, Thomas - M.D., F.R.S",http://www.flickr.com/photos/britishlibrary/ta...
4006496,London,1898.0,W. Heinemann,"Cleo the Magnificent; or, The Muse of the Real...","Z., Z.",http://www.flickr.com/photos/britishlibrary/ta...
4006497,London,1894.0,W. Heinemann,A Drama in Dutch. [A novel.] By Z. Z. [i.e. Lo...,"Z., Z.",http://www.flickr.com/photos/britishlibrary/ta...
4006498,London,1896.0,W. Heinemann,The World and a Man. [A novel.] By 'Z. Z. [i.e...,"Z., Z.",http://www.flickr.com/photos/britishlibrary/ta...
4006577,London,1832.0,NaN,"Polish Exile. Poems, translated by H. Montriou","ZABA, Napoleon Felix.",http://www.flickr.com/photos/britishlibrary/ta...
4015049,London,1889.0,Blackie & Son,Commercial Geography: based on the latest rese...,"ZEHDEN, Carl.",http://www.flickr.com/photos/britishlibrary/ta...
4027249,London,1803.0,NaN,The History of the Invasion of Switzerland by ...,"ZSCHOKKE, Johann Heinrich Daniel.",http://www.flickr.com/photos/britishlibrary/ta...
4029050,London,1899.0,T. F. Unwin,From the Alps to the Andes: being the autobiog...,"ZURBRIGGEN, Mattias.",http://www.flickr.com/photos/britishlibrary/ta...
4029064,London,1869.0,NaN,Mountain Adventures in the various countries o...,"ZURCHER, Frédéric - and MARGOLLÉ (Élie)",http://www.flickr.com/photos/britishlibrary/ta...
4030632,London,1831.0,NaN,"Calmuc Tartary; or, a Journey from Sarepta to ...","ZWICK, Heinrich August.",http://www.flickr.com/photos/britishlibrary/ta...
4041055,London,1801.0,"Vernor & Hood, etc.","Hudibras, in three parts ... With large annota...","BUTLER, Samuel - the Poet",http://www.flickr.com/photos/britishlibrary/ta...
4063671,London,1896.0,Richard Bentley & Son,Honor Ormthwaite. By the author of “Lady Jean'...,"KEDDIE, Henrietta.",http://www.flickr.com/photos/britishlibrary/ta...
4079262,London,1879.0,NaN,The Canadian farmer. A missionary incident. [S...,"YATES, William Joseph H.",http://www.flickr.com/photos/britishlibrary/ta...
4112839,London,NaN,Willoughby & Co.,The Vicar of Wakefield ... And a prefatory mem...,"Goldsmith, Oliver",http://www.flickr.com/photos/britishlibrary/ta...
4114390,London,1708.0,NaN,"THe Unfortunate Dutchess of Malfy, or, The Unn...","WEBSTER, John - Dramatist|SCOTT, Michael - of ...",http://www.flickr.com/photos/britishlibrary/ta...
4114889,London,NaN,NaN,"The 5 Alls. A collection of stories, charades,...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4114986,London,1777.0,J. Wenman,[Barbarossa. A tragedy. As it is performed at ...,"BROWN, John - Vicar of Newcastle-upon-Tyne",http://www.flickr.com/photos/britishlibrary/ta...
4116063,London,1866.0,[John Dicks],"Edith Heron; or, the Earl and the countess. [B...","HERON, Edith.",http://www.flickr.com/photos/britishlibrary/ta...
4117583,London,1894.0,T. Fisher Unwin,The Wish. A novel by Hermann Sudermann. Transl...,"SUDERMANN, Hermann.",http://www.flickr.com/photos/britishlibrary/ta...
4117752,London,1883.0,Trübner & Co.,"A System of Mineralogy ... Fifth edition, rewr...","DANA, James Dwight.",http://www.flickr.com/photos/britishlibrary/ta...
4157746,London,1811.0,F. C. and J. Rivington,"The New Chronicles of England and France, in t...","FABYAN, Robert.",http://www.flickr.com/photos/britishlibrary/ta...
4158088,London,1838.0,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.",http://www.flickr.com/photos/britishlibrary/ta...
4159563,London,NaN,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...",http://www.flickr.com/photos/britishlibrary/ta...
4160339,London,1834.0,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,http://www.flickr.com/photos/britishlibrary/ta...

In [28]:
data.loc[data['Place of Publication']== 'Oxford']

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
111455,Oxford,NaN,J. & J. Fletcher,"The Frogs, a comedy. Translated ... by C. Duns...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
192427,Oxford,1846.0,John Henry Parker,The Baptistery ... By the author of “The Cathe...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
262687,Oxford,1887.0,Rowbottom & Son,The History of Constitutional Progress during ...,"BELLEWES, George Oliver - and DEVENISH (Willia...",http://www.flickr.com/photos/britishlibrary/ta...
686597,Oxford,1818.0,[Clarendon Press,The History of Chilton in the County of Buking...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
962896,Oxford,1892.0,NaN,Notes on the Oxfordshire Domesday [with a summ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
991105,Oxford,1897.0,Clarendon Press,"Hindu Manners, Customs and Ceremonies ... Tran...","DUBOIS, Jean Antoine.",http://www.flickr.com/photos/britishlibrary/ta...
991106,Oxford,1899.0,Clarendon Press,"Hindu Manners, Customs, and Ceremonies ... Tra...","DUBOIS, Jean Antoine.",http://www.flickr.com/photos/britishlibrary/ta...
1211883,Oxford,1895.0,B. H. Blackwell,A Short Constitutional History of England ... ...,"FEILDEN, Henry Saint Clair.",http://www.flickr.com/photos/britishlibrary/ta...
1259903,Oxford,1895.0,Clarendon Press,An Introduction to Chemical Crystallography .....,"FOCK, Andreas.",http://www.flickr.com/photos/britishlibrary/ta...
1341190,Oxford,1892.0,Clarendon Press,Wise Words and Quaint Counsels of Thomas Fulle...,"FULLER, Thomas - D.D., Prebendary of Salisbury",http://www.flickr.com/photos/britishlibrary/ta...
1553618,Oxford,1640.0,W. Turner,"Sicily and Naples, or, the fatall union. A tra...","H., S. - A.B., e C. Ex",http://www.flickr.com/photos/britishlibrary/ta...
1565531,Oxford,1893.0,Clarendon Press,Voyages of the Elizabethan Seamen to America ....,"Hakluyt, Richard",http://www.flickr.com/photos/britishlibrary/ta...
1565534,Oxford,1893.0,Clarendon Press,Voyages of the Elizabethan Seamen to America ....,"Hakluyt, Richard",http://www.flickr.com/photos/britishlibrary/ta...
1630483,Oxford,1885.0,NaN,Remarks and Collections of Thomas Hearne ... E...,"HEARNE, Thomas - Antiquary",http://www.flickr.com/photos/britishlibrary/ta...
1635714,Oxford,1829.0,D. A. Talboys,A Manual of Ancient History ... Translated fro...,"HEEREN, Arnold Hermann Ludwig.",http://www.flickr.com/photos/britishlibrary/ta...
1635730,Oxford,1829.0,NaN,A sketch of the political history of Ancient G...,"HEEREN, Arnold Hermann Ludwig.",http://www.flickr.com/photos/britishlibrary/ta...
1664649,Oxford,1824.0,NaN,"The History of Herodotus, literally translated...",Herodotus.,http://www.flickr.com/photos/britishlibrary/ta...
1664652,Oxford,1846.0,NaN,"[The nine books of the History of Herodotus, t...",Herodotus.,http://www.flickr.com/photos/britishlibrary/ta...
1688742,Oxford,1858.0,NaN,"The Hindoo Maiden, a tale, in verse. [By J. A....",NaN,http://www.flickr.com/photos/britishlibrary/ta...
1781291,Oxford,1826.0,NaN,[The history of the rebellion and civil wars i...,"Clarendon, Edward Hyde - Earl of",http://www.flickr.com/photos/britishlibrary/ta...
1781292,Oxford,1827.0,NaN,[The history of the rebellion and civil wars i...,"Clarendon, Edward Hyde - Earl of",http://www.flickr.com/photos/britishlibrary/ta...
1818869,Oxford,1663.0,H. Hall for R. Davis,Verses spoken at the appearance of the King an...,"IRELAND, Thomas - Student of Christ Church",http://www.flickr.com/photos/britishlibrary/ta...
1887400,Oxford,1888.0,Clarendon Press,"Wit and Wisdom of Samuel Johnson, selected and...","JOHNSON, Samuel - LL.D|JOHNSON, Samuel - LL.D",http://www.flickr.com/photos/britishlibrary/ta...
2102452,Oxford,1889.0,Clarendon Press,Chronicon Galfridi Le Baker de Swynebroke. Edi...,"LE BAKER, Galfridus - de Swinbroke",http://www.flickr.com/photos/britishlibrary/ta...
2202381,Oxford,1844.0,J. H. Parker,The History of Rome by Titus Livius. With Engl...,Livy.,http://www.flickr.com/photos/britishlibrary/ta...
2299204,Oxford,1658.0,Re-Printed by Hen. Hall [for] Ric. Davis,Two Plaies. The City Match. A comoedy. And The...,"M., J. - of Ch. Ch. in Oxon",http://www.flickr.com/photos/britishlibrary/ta...
2502001,Oxford,1893.0,B. H. Blackwell,Milton's Lycidas: lines 15-84: in Theocritean ...,"Milton, John",http://www.flickr.com/photos/britishlibrary/ta...
2539667,Oxford,NaN,A. Thos. Shrimpton & Son,The Pictorial and Historical Gossiping Guide t...,"MOORE, James J.",http://www.flickr.com/photos/britishlibrary/ta...
2573707,Oxford,1830.0,NaN,"The History and Antiquities of the Doric Race,...","MUELLER, Carl Otfried.",http://www.flickr.com/photos/britishlibrary/ta...
2698099,Oxford,1892.0,J. Parker & Co.,"Royal Letters addressed to Oxford, and now exi...","OGLE, Octavius.",http://www.flickr.com/photos/britishlibrary/ta...
2714138,Oxford,1823.0,W. Baxter,"Stonehenge. A poem. [Signed, Sir Oracle, Ox. C...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
2740260,Oxford,1847.0,John Henry Parker,A Hand-book for Visitors to Oxford. [By John H...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
2740310,Oxford,1859.0,Slatter & Rose,"Oxford during the last century, being two seri...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
2740334,Oxford,1824.0,NaN,"The Perambulation of Oxford, Blenheim, and Nun...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
2740636,Oxford,1818.0,NaN,"The Oxford Spy; a dialogue, in verse.-(Dialogu...",NaN,http://www.flickr.com/photos/britishlibrary/ta...
2740891,Oxford,1778.0,Printed for the Author,The Oxonian. A poem. In imitation of “The Sple...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
2779568,Oxford,1882.0,Parker & Co.,"The History of Dorchester, Oxfordshire: Britis...","PARKER, John Henry - C.B",http://www.flickr.com/photos/britishlibrary/ta...
3036588,Oxford,1892.0,Clarendon Press,Lancaster and York: a century of English histo...,"RAMSAY, James Henry - Sir, Bart",http://www.flickr.com/photos/britishlibrary/ta...
3039451,Oxford,1875.0,NaN,"A History of England, principally in the seven...","Ranke, Leopold von",http://www.flickr.com/photos/britishlibrary/ta...
3354959,Oxford,1766.0,D. Prince,Observations and Conjectures upon some passage...,"Shakespeare, William",http://www.flickr.com/photos/britishlibrary/ta...
3519690,Oxford,1893.0,Clarendon Press,Selections from Strabo. With an introduction o...,NaN,http://www.flickr.com/photos/britishlibrary/ta...
3557266,Oxford,1892.0,Clarendon Press,"Swift, Selections from his Works. Edited with ...","Swift, Jonathan",http://www.flickr.com/photos/britishlibrary/ta...
3605102,Oxford,NaN,NaN,The Oxford Thackeray. With illustrations. [Edi...,"Thackeray, William Makepeace",http://www.flickr.com/photos/britishlibrary/ta...
3999294,Oxford,1885.0,Clarendon Press,York Plays. The plays performed by the Crafts ...,NaN,http://www.flickr.com/photos/britishlibrary/ta...

<b>We see some row with Place of Publication as 'London' and 'Oxford' have unnecessary information.</b>

<b>Clean this column in one go use str.contains() to get a boolean mask.</b>

In [29]:
london = data['Place of Publication'].str.contains('London')
london.head()

Identifier
206    True
216    True
218    True
472    True
480    True
Name: Place of Publication, dtype: bool

In [30]:
oxford = data['Place of Publication'].str.contains('Oxford')
oxford.head()

Identifier
206    False
216    False
218    False
472    False
480    False
Name: Place of Publication, dtype: bool

In [31]:
# Combine all with NumPy
data['Place of Publication'] = np.where(london, 'London',
                                      np.where(oxford, 'Oxford',
                                               data['Place of Publication'].str.replace('-', ' ')))
data.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

<b>There is some dirt in other columns too</b><br />
<b>To clean the dirt from entire dataset we use 'applymap' method</b>

# Next For 'applymap' method